### ISSUE TITLE
Deploy to Bintray

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/cryptomator-linux#1]
If successfully built, the AppImage should be deployed to Bintray.

**Comment by probonopd** [comment]
Possibly GitHub Releases is another option. This tool makes it easy:
https://github.com/probonopd/uploadtool/

**Comment by overheadhunter** [comment]
@probonopd We will take a look at it. Currently we use Bintray for our Mac and Windows binaries, so this would be a bit more consistent. Does your uploadtool replace previous snapshots/nightlies or does it create a new gh release each time?

But before we decide how to distribute, we need to fix the build itself. Currently [appimagetool fails](https://travis-ci.org/cryptomator/cryptomator-linux/builds/357429700#L566) with `mksquashfs: invalid option` for an unknown reason. Any idea what might be the cause?

I'm currently still trying to use the lightweight [container-based environment](https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System) (`sudo: false`), but apparently it lacks FUSE support (that's why I'm [`--appimage-extract`ing appimagetool](https://github.com/cryptomator/cryptomator-linux/blob/38dab31db70a7f68030aee2cb246b3d5e81373d2/build.sh#L34) in my build.sh). I understand that AppImage requires FUSE at runtime, but other than that there should be no reason I need it during the build. Am I right?

**Comment by overheadhunter** [comment]
Ok found the cause for mksquashfs failing in [this issue](https://github.com/AppImage/AppImageKit/issues/295). Will try to use the patched version bundled with appimagetool.

Update: Fixed the build. AppImage would be ready to upload. Either to Bintray or to GitHub Releases.
