### ISSUE TITLE
missing desktop integration

### ISSUE THREAD

**Issue by marianoju** [cryptomator/cryptomator-linux#11]
The latest version of Cryptomator for Linux (1.4.0) has (so far) only been released as an AppImage. While I understand the benefits that the AppImage format provides to developers I am missing the desktop integration that used to come with Debian packages. Can a desktop integration be expected in the near future?

**Comment by overheadhunter** [comment]
Can you elaborate on what kind of integration you are missing?

**Comment by overheadhunter** [comment]
@marianoju Please refer to `appimaged` or `AppImageLauncher` if you want [such desktop integration features](https://docs.appimage.org/user-guide/run-appimages.html#integrating-appimages-into-the-desktop). AppImages can be auto-updating and appear in the applications menu etc.
