### ISSUE TITLE
1.5.1 AppImage broken, won't start

### ISSUE THREAD

**Issue by moppman** [cryptomator/cryptomator-linux#22]
https://bintray.com/cryptomator/cryptomator/cryptomator-linux/1.5.1#files/1.5.1

AppImage won't start. `AppRun -> Cryptomator` looks like a broken symlink.
See screenshot:
![Screenshot_2020-04-21_20-20-30](https://user-images.githubusercontent.com/10085380/79900193-2433bb00-840e-11ea-8720-a9c80b06fdf0.png)

**Comment by overheadhunter** [comment]
Oh you're right, the file structure has changed!

We can fix this in the AppImage, no need to create a new release version for this.

**Comment by overheadhunter** [comment]
Should be fixed with this [reuploaded version](https://dl.bintray.com/cryptomator/cryptomator/1.5.1/cryptomator-1.5.1-x86_64.AppImage).
