### ISSUE TITLE
Appimage doesn't include update information

### ISSUE THREAD

**Issue by Sugarcrisp-ui** [cryptomator/cryptomator-linux#29]
I really like the cryptomator appimage that you provide.  I would like to request that you include the update information with your appimage to allow users to take advantage of programs like appimageupdater to ensure the program is kept up to date

**Comment by overheadhunter** [comment]
To be more precise: The update information is included, but it is wrong. Running the appimage with `--appimage-updateinformation` yields:

```
bintray-zsync|cryptomator|cryptomator|cryptomator-linux|cryptomator-${BUILD_VERSION}-x86_64.AppImage.zsync
```

**Comment by Sugarcrisp-ui** [comment]
Hello Sebastian,

Based on your findings, you believe it should be working?

Brett

**Comment by Sugarcrisp-ui** [comment]
Hey Sebastian,

I was following up with Cryptomator and one other software from a
different vendor.  I re-read your email and realized that it is working and
responded to the wrong one.  Thanks for the follow up and for packaging a
great software.

Brett

**Comment by overheadhunter** [comment]
`${BUILD_VERSION}` is wrong, as explained [here](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#bintray-zsync):

> Path where the zsync file is stored on Bintray (MUST NOT change from version to version). Note the use of the Bintray feature _latestVersion to facilitate this

Therefore we should change this as follows:

```diff
- ./tools/appimagekit/squashfs-root/AppRun Cryptomator.AppDir cryptomator-${BUILD_VERSION}-x86_64.AppImage -u "bintray-zsync|cryptomator|cryptomator|cryptomator-linux|cryptomator-${BUILD_VERSION}-x86_64.AppImage.zsync"
+ ./tools/appimagekit/squashfs-root/AppRun Cryptomator.AppDir cryptomator-${BUILD_VERSION}-x86_64.AppImage -u 'bintray-zsync|cryptomator|cryptomator|cryptomator-linux|cryptomator-_latestVersion-x86_64.AppImage.zsync'
```
