### ISSUE TITLE
Migrate from bintray to github releases

### ISSUE THREAD

**Issue by infeo** [cryptomator/cryptomator-linux#30]
Due to announced [shutdown of brintray](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), there is the need of moving our CI publishing from to another host.

Github offers with Github releases a convinient way of doing so, especially since this repository already uses Github CI.

Before flipping the switch there are some preperations needed:
* [x] Update the AppImage zsync link
* [x] Release and push a last version of the AppImage to Bintray with the changed update link included

**Comment by infeo** [comment]
Some tests revealed, that the current bintray update information is already incorrect, i.e. users would not be notified, even if we publish a new release to bintray.

Using the [appimage update tool](https://github.com/AppImage/AppImageUpdate) to show update info 
```
user@os:~/Downloads$ ./appimageupdatetool-x86_64.AppImage -d ./cryptomator-1.5.11-x86_64.AppImage 

Parsing file: ./cryptomator-1.5.11-x86_64.AppImage
AppImage type: 2
Raw update information: bintray-zsync|cryptomator|cryptomator|cryptomator-linux|cryptomator-_latestVersion-x86_64.AppImage.zsync
Update information type: ZSync via Bintray
Assembled ZSync URL: https://dl.bintray.com/cryptomator/cryptomator/cryptomator-1.5.12-x86_64.AppImage.zsync
```
and checking for updates
```
user@os:~/Downloads$ ./appimageupdatetool-x86_64.AppImage -j ./cryptomator-1.5.11-x86_64.AppImage 
zsync2: 
zsync2: Reading and/or parsing .zsync file failed!
Error checking for changes!
```
results in an error.

It is caused by a long-ago change, that releases are published under their own library, meaning the correct url would be `https://dl.bintray.com/cryptomator/cryptomator/1.5.12/cryptomator-1.5.12-x86_64.AppImage.zsync`.

If we make a last release to bintray, we should consider to change the release path manually.

**Comment by overheadhunter** [comment]
Any objections against re-releasing 1.5.12 app image?

**Comment by infeo** [comment]
No objections. But the issue should be closed, after all tasks are finished. And the release to gh and bintray is one of the tasks.

**Comment by overheadhunter** [comment]
Done. Now copying updated appimage to cryptomator/cryptomator releases.
