### ISSUE TITLE
Embedd AppStream metadata

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/cryptomator-linux#4]
See [AppImage Specification](https://github.com/AppImage/AppImageSpec/blob/871cea4182ac896a5423d37ac7261f130d12a25f/draft.md#appstream).

**Comment by overheadhunter** [comment]
See also: https://github.com/cryptomator/cryptomator/issues/328

**Comment by overheadhunter** [comment]
First version added in 205c47e:

https://github.com/cryptomator/cryptomator-linux/blob/205c47ed958287b51fcf215aa989b5a99947dc8d/resources/appimage/cryptomator.appdata.xml#L4-L8

**Comment by x80486** [comment]
So, this: `org.cryptomator.cryptomator` ...is going to be your official Application ID, right?

Where is this file in the released artifacts for Linux? It would be great to have it along with some [SVG](https://github.com/x80486/flathub/blob/org.cryptomator.Cryptomator/org.cryptomator.Cryptomator.svg/) version of the icon.

Moreover, take a look at [this one](https://github.com/x80486/flathub/blob/org.cryptomator.Cryptomator/org.cryptomator.Cryptomator.appdata.xml/), you might want to pull some bits from it and merge it with this one.
