### ISSUE TITLE
Switching to JavaFX 11: Wayland support needs additional flag

### ISSUE THREAD

**Issue by infeo** [cryptomator/cryptomator-linux#9]
When we finally switch to JavaFX 11, we should be aware of the bug JavaFX exposes on linux systems using Wayland as display server (see https://github.com/javafxports/openjdk-jfx/blob/jfx-11/doc-files/release-notes-11.md#javafx-crashes-with-openjdk-11-on-ubuntu-1804-with-wayland).

As a workaround we should either detect before cryptomator is starting which display server is used (e.g. by a startupscript) or should use always the announced workaround with `java -Djdk.gtk.version=2 ...`.

**Comment by overheadhunter** [comment]
According to [JDK-8210411](https://bugs.openjdk.java.net/browse/JDK-8210411) this will be fixed with OpenJFX 12.

**Comment by overheadhunter** [comment]
Backported to OpenJFX 11.0.2 ([JDK-8216292](https://bugs.openjdk.java.net/browse/JDK-8216292)), therefore resolved.

**Comment by overheadhunter** [comment]
Reopening as the upstream fix doesn't work (see https://github.com/cryptomator/cryptomator/issues/846#issuecomment-475979998). We have to use GTK 2.

**Comment by overheadhunter** [comment]
Seems like we can't satisfy every user. For now we will include the flag again.

#### Users who need the flag:
* https://github.com/cryptomator/cryptomator/issues/846#issuecomment-475979998 (Fedora 29)
* https://github.com/cryptomator/cryptomator/issues/1167#issuecomment-624038268 (Elementary OS 5.1.4)
* https://github.com/cryptomator/cryptomator/issues/1160 (Chrome OS)

#### Users who need to remove the flag:
* ~~https://github.com/cryptomator/cryptomator/issues/1121#issuecomment-616379476 (Ubuntu 19.10)~~ apparently not using appimage
* https://github.com/cryptomator/cryptomator/issues/1230#issuecomment-648725946 (Debian Buster)
* https://github.com/cryptomator/cryptomator/issues/1230#issuecomment-636698739 (Arch w/ KDE Plasma)
